name: graham kennedy
favicon: null
layout_spectrum: 0
typography_spectrum: 0.51829
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#5f5f5f'
    - '#a6a6a6'
    - '#41afaa'
  brandStrength: 0
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
